<?php
// backend/api/ai/catalog.php
// AI-Assisted Book Cataloging using Google Gemini API
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../includes/response.php';
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/GeminiService.php';
require_once __DIR__ . '/../../includes/activity_logger.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    Response::error('Method not allowed. Only POST is supported.', 405);
}

// Require Admin or Super Admin
$user = JWT::requireRole(['admin', 'superadmin']);

$input = Utils::getJsonInput();
$title = trim($input['title'] ?? '');
$author = trim($input['author'] ?? '');

if (empty($title) && empty($author)) {
    Response::badRequest('Please provide at least a book title or author name for AI cataloging.');
}

try {
    $gemini = new GeminiService();
    
    $prompt = "You are an expert library cataloger. Given the book title '{$title}' and author '{$author}', provide realistic, structured bibliographic metadata in strictly valid JSON format without any markdown or code fences.\n";
    $prompt .= "Return only a single JSON object with these exact keys:\n";
    $prompt .= "{\n";
    $prompt .= '  "title": "Full Official Book Title",' . "\n";
    $prompt .= '  "author": "Primary Author Name",' . "\n";
    $prompt .= '  "category": "Standard Library Category (e.g. Fiction, Science, Philippine History, Computer Science, Literature, Biography)",' . "\n";
    $prompt .= '  "publisher": "Reputable Publisher Name",' . "\n";
    $prompt .= '  "year": 2020,' . "\n";
    $prompt .= '  "isbn": "978-XXXXXXXXXX",' . "\n";
    $prompt .= '  "description": "Engaging 2-3 sentence overview of the book contents.",' . "\n";
    $prompt .= '  "format": "Paperback",' . "\n";
    $prompt .= '  "shelf_location": "Suggested shelf location code (e.g. Shelf A-1, Reference Sec)"' . "\n";
    $prompt .= "}\n";

    $rawResponse = $gemini->generateResponse($prompt, [], [], 'cataloging');

    if (!$rawResponse) {
        // Fallback default metadata template if API key is unconfigured or rate limited
        $generatedData = [
            'title' => !empty($title) ? ucwords($title) : 'Sample Book Title',
            'author' => !empty($author) ? ucwords($author) : 'Unknown Author',
            'category' => 'General Collection',
            'publisher' => 'National Book Publishing',
            'year' => (int)date('Y'),
            'isbn' => '978-' . rand(100, 999) . '-' . rand(10000, 99999) . '-' . rand(1, 9),
            'description' => 'A curated academic and reading resource for the municipal library collection.',
            'format' => 'Paperback',
            'shelf_location' => 'Shelf G-' . rand(1, 10)
        ];
    } else {
        // Clean markdown code blocks if returned
        $cleanJson = preg_replace('/```(?:json)?\s*|\s*```/', '', trim($rawResponse));
        $decoded = json_decode($cleanJson, true);

        if ($decoded && is_array($decoded) && isset($decoded['title'])) {
            $generatedData = [
                'title' => $decoded['title'] ?? $title,
                'author' => $decoded['author'] ?? $author,
                'category' => $decoded['category'] ?? 'General',
                'publisher' => $decoded['publisher'] ?? 'Standard Publications',
                'year' => isset($decoded['year']) ? (int)$decoded['year'] : (int)date('Y'),
                'isbn' => $decoded['isbn'] ?? ('978-' . rand(100, 999) . '-' . rand(10000, 99999) . '-' . rand(1, 9)),
                'description' => $decoded['description'] ?? 'Bibliographic record generated by AI cataloger.',
                'format' => $decoded['format'] ?? 'Paperback',
                'shelf_location' => $decoded['shelf_location'] ?? 'Shelf A-1'
            ];
        } else {
            // Fallback parsing
            $generatedData = [
                'title' => ucwords($title),
                'author' => ucwords($author),
                'category' => 'General Collection',
                'publisher' => 'Philippine Educational Press',
                'year' => (int)date('Y'),
                'isbn' => '978-' . rand(100, 999) . '-' . rand(10000, 99999) . '-' . rand(1, 9),
                'description' => 'Standard library acquisition record.',
                'format' => 'Paperback',
                'shelf_location' => 'Main Shelf'
            ];
        }
    }

    logActivity(
        $user['id'],
        'ai_catalog',
        'Books',
        "Librarian invoked AI cataloging query for: '{$title}' by '{$author}'"
    );

    Response::success($generatedData, 'AI metadata retrieved successfully. Please review and edit before saving.');

} catch (Exception $e) {
    Response::error('AI Cataloging service error: ' . $e->getMessage());
}
