// src/pages/admin/AdminBooks.tsx
import React, { useState, useEffect } from 'react';
import api from '../../lib/api';
import DataTable from '../../components/common/DataTable';
import Modal from '../../components/common/Modal';
import Button from '../../components/common/Button';
import { BookOpen, Edit, Trash2, Plus, Info, CheckCircle, XCircle, Search, Sparkles, X, Loader2, Archive, RotateCcw } from 'lucide-react';
import { fetchBookByIsbn } from '../../lib/bookApi';
import { useToast } from '../../context/ToastContext';

export const AdminBooks: React.FC = () => {
  const toast = useToast();
  const [books, setBooks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeDropdownId, setActiveDropdownId] = useState<number | null>(null);

  // Click outside to close dropdowns
  useEffect(() => {
    const handleOutsideClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest('.actions-dropdown-container')) {
        setActiveDropdownId(null);
      }
    };
    document.addEventListener('click', handleOutsideClick);
    return () => document.removeEventListener('click', handleOutsideClick);
  }, []);

  // Modals state
  const [addModalOpen, setAddModalOpen] = useState(false);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [selectedBook, setSelectedBook] = useState<any | null>(null);
  const [deleteConfirmBook, setDeleteConfirmBook] = useState<any | null>(null);
  const [archiveConfirmBook, setArchiveConfirmBook] = useState<any | null>(null);
  const [archiveLoading, setArchiveLoading] = useState(false);

  // Form states
  const [formData, setFormData] = useState({
    title: '',
    author: '',
    isbn: '',
    category: 'Fiction',
    year: new Date().getFullYear(),
    description: '',
    cover_image: '',
    total_copies: 1
  });

  const [formLoading, setFormLoading] = useState(false);
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  // Automated ISBN lookup state
  const [isbnInput, setIsbnInput] = useState('');
  const [fetchingDetails, setFetchingDetails] = useState(false);
  const [fetchStatus, setFetchStatus] = useState<{ type: 'success' | 'error' | 'info'; message: string } | null>(null);

  const handleFetchBookDetails = async () => {
    const clean = isbnInput.trim().replace(/[-\s]/g, '');
    if (!clean) {
      setFetchStatus({ type: 'error', message: 'Please enter a valid ISBN code.' });
      return;
    }
    setFetchingDetails(true);
    setFetchStatus({ type: 'info', message: 'Searching catalog databases...' });
    try {
      const details = await fetchBookByIsbn(clean);
      setFormData((prev) => ({
        ...prev,
        title: details.title || prev.title,
        author: details.author || prev.author,
        isbn: details.isbn || prev.isbn,
        category: details.category || prev.category,
        year: details.year || prev.year,
        description: details.description || prev.description,
        cover_image: details.cover_image || prev.cover_image
      }));
      setFetchStatus({
        type: 'success',
        message: `Found "${details.title}" (Genre: ${details.category}) via ${details.source === 'google' ? 'Google Books' : 'Open Library'}!`
      });
    } catch (err: any) {
      setFetchStatus({
        type: 'error',
        message: err.message || 'Could not retrieve book details for this ISBN.'
      });
    } finally {
      setFetchingDetails(false);
    }
  };

  const fetchBooks = async () => {
    setLoading(true);
    try {
      const response = await api.get('/books/getAll', { params: { limit: 100 } });
      if (response.data && response.data.success) {
        setBooks(response.data.data.books);
      }
    } catch (err) {
      console.error('Failed to query catalog:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      fetchBooks();
    }, 0);
    return () => clearTimeout(timer);
  }, []);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: name === 'year' || name === 'total_copies' ? parseInt(value) || 0 : value
    }));
  };

  const handleAutoGenerateDescription = () => {
    const { title, author, category, year } = formData;
    if (!title || !author) return;

    const templates = [
      `"${title}" is a compelling ${category.toLowerCase()} work written by the distinguished author ${author} in ${year}. Set against a richly woven backdrop, this masterpiece explores the intricate human condition, challenging readers' perceptions through its powerful storytelling. An exceptional addition to the library, it remains highly recommended for anyone interested in deep, thought-provoking literature.`,
      
      `Written by the acclaimed author ${author} and published in ${year}, this outstanding ${category.toLowerCase()} book, "${title}", delivers a masterful narrative filled with depth and intellect. It delves into profound themes and captivating character development that keeps readers engrossed from the very first page. A landmark text in its genre, perfect for local students and avid readers alike.`,
      
      `An immersive and exquisitely crafted ${category.toLowerCase()} classic, "${title}" by ${author} (${year}) stands as a stellar contribution to modern literature. The book skillfully weaves elements of suspense, discovery, and philosophy to create a memorable and highly recommended reading experience. An essential volume for the Balingasag Municipal Public Library shelves.`,
      
      `In this highly acclaimed ${category.toLowerCase()} volume, "${title}", published in ${year}, the renowned author ${author} presents a brilliantly researched and captivating perspective. Known for its engaging prose and stunning emotional resonance, the book leads readers through an unforgettable journey of learning and personal growth. A highly sought-after reference in our catalog.`
    ];

    const hash = (title.length + author.length + (parseInt(year.toString()) || 0)) % templates.length;
    const generated = templates[hash];
    
    setFormData((prev) => ({
      ...prev,
      description: generated
    }));
  };

  const handleOpenAdd = () => {
    setFeedback(null);
    setIsbnInput('');
    setFetchStatus(null);
    setFormData({
      title: '',
      author: '',
      isbn: '',
      category: 'Fiction',
      year: new Date().getFullYear(),
      description: '',
      cover_image: '',
      total_copies: 1
    });
    setAddModalOpen(true);
  };

  const handleOpenEdit = (book: any) => {
    setFeedback(null);
    setSelectedBook(book);
    setFormData({
      title: book.title,
      author: book.author,
      isbn: book.isbn,
      category: book.category,
      year: book.year,
      description: book.description || '',
      cover_image: book.cover_image || '',
      total_copies: book.total_copies
    });
    setEditModalOpen(true);
  };

  const handleAddSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFeedback(null);
    setFormLoading(true);
    try {
      const response = await api.post('/books/create', formData);
      if (response.data && response.data.success) {
        setAddModalOpen(false);
        fetchBooks();
        toast.success('Book catalog record successfully created!');
      }
    } catch (err: any) {
      const errMsg = err.response?.data?.message || err.message || 'Failed to create book.';
      toast.error(errMsg);
      setFeedback({
        type: 'error',
        message: errMsg
      });
    } finally {
      setFormLoading(false);
    }
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedBook) return;
    
    setFeedback(null);
    setFormLoading(true);
    try {
      const response = await api.post('/books/update', {
        id: selectedBook.id,
        ...formData
      });
      if (response.data && response.data.success) {
        setEditModalOpen(false);
        fetchBooks();
        toast.success('Book catalog modifications successfully saved!');
      }
    } catch (err: any) {
      const errMsg = err.response?.data?.message || err.message || 'Failed to save modifications.';
      toast.error(errMsg);
      setFeedback({
        type: 'error',
        message: errMsg
      });
    } finally {
      setFormLoading(false);
    }
  };

  const handleOpenDeleteConfirm = (book: any) => {
    const activeBorrows = book.total_copies - book.available_copies;
    if (activeBorrows > 0) {
      toast.warn(`Deletion BLOCKED. The title currently has ${activeBorrows} physical copy loans in active circulation.`);
      return;
    }
    setDeleteConfirmBook(book);
  };

  const handleDeleteExecute = async (book: any) => {
    try {
      const response = await api.post(`/books/delete?id=${book.id}`);
      if (response.data && response.data.success) {
        fetchBooks();
        toast.success('Book catalog record deleted successfully.');
      }
    } catch (err: any) {
      const errMsg = err.response?.data?.message || err.message || 'Failed to delete book.';
      toast.error(errMsg);
    }
  };

  const handleOpenArchiveConfirm = (book: any) => {
    if (book.status !== 'archived') {
      const activeBorrows = book.total_copies - book.available_copies;
      if (activeBorrows > 0) {
        toast.warn(`Archival BLOCKED. The title currently has ${activeBorrows} physical copy loans in active circulation.`);
        return;
      }
    }
    setArchiveConfirmBook(book);
  };

  const handleArchiveExecute = async (book: any) => {
    setArchiveLoading(true);
    try {
      const response = await api.post('/books/archive', {
        id: book.id
      });
      if (response.data && response.data.success) {
        fetchBooks();
        toast.success(response.data.message || 'Book status toggled successfully.');
      }
    } catch (err: any) {
      toast.error(err.response?.data?.message || err.message || 'Failed to toggle book archival status.');
    } finally {
      setArchiveLoading(false);
      setArchiveConfirmBook(null);
    }
  };

  const columns = [
    {
      header: 'Book details',
      accessor: (row: any) => (
        <div className="flex items-center gap-3.5">
          <div className="h-11 w-8.5 bg-slate-50 border border-slate-100 rounded flex items-center justify-center flex-shrink-0">
            {row.cover_image && row.cover_image.startsWith('http') ? (
              <img src={row.cover_image} alt={row.title} className="h-full w-full object-cover" />
            ) : (
              <BookOpen className="h-5 w-5 text-slate-300" />
            )}
          </div>
          <div>
            <p className="font-extrabold text-slate-700 leading-snug line-clamp-1">{row.title}</p>
            <p className="text-[10px] text-slate-400 font-semibold">Author: {row.author} | ISBN: {row.isbn}</p>
          </div>
        </div>
      ),
      sortable: true,
      sortKey: 'title'
    },
    {
      header: 'Genre',
      accessor: 'category',
      sortable: true,
      className: 'text-xs capitalize font-semibold'
    },
    {
      header: 'Inventory Stock',
      accessor: (row: any) => (
        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-bold rounded-full border ${
          row.available_copies > 0 ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-rose-50 text-rose-600 border-rose-100'
        }`}>
          {row.available_copies > 0 ? <CheckCircle className="h-3.5 w-3.5" /> : <XCircle className="h-3.5 w-3.5" />}
          {row.available_copies} of {row.total_copies} available
        </span>
      )
    },
    {
      header: 'Status',
      accessor: (row: any) => {
        const statuses = {
          available: 'bg-emerald-50 text-emerald-600 border-emerald-100',
          unavailable: 'bg-rose-50 text-rose-600 border-rose-100',
          archived: 'bg-slate-100 text-slate-600 border-slate-200',
        };
        const statusMap = row.status as keyof typeof statuses;
        return (
          <span className={`px-2 py-0.5 border rounded-full text-[10px] font-bold capitalize ${statuses[statusMap] || 'bg-slate-50 text-slate-500 border-slate-100'}`}>
            {row.status}
          </span>
        );
      },
      sortable: true,
      sortKey: 'status'
    },
    {
      header: 'Actions',
      accessor: (row: any) => {
        const isOpen = activeDropdownId === row.id;
        return (
          <div className="relative inline-block text-left actions-dropdown-container">
            <Button
              variant="outline"
              size="sm"
              onClick={(e) => {
                e.stopPropagation();
                setActiveDropdownId(isOpen ? null : row.id);
              }}
              className="px-3.5 h-10 text-xs border-slate-200 hover:bg-slate-50 text-slate-700 hover:text-emerald-700 rounded-xl flex items-center gap-1.5 font-bold shadow-sm animate-fade-in"
            >
              <span>Actions</span>
              <span className="text-[9px] transition-transform duration-200" style={{ transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)' }}>▼</span>
            </Button>
            
            {isOpen && (
              <div 
                className="absolute right-0 mt-1.5 w-36 rounded-xl bg-white border border-slate-100 shadow-xl py-1.5 z-[100] animate-fade-in text-left pointer-events-auto"
                onClick={(e) => e.stopPropagation()}
              >
                <button
                  type="button"
                  onClick={() => {
                    setActiveDropdownId(null);
                    handleOpenEdit(row);
                  }}
                  className="w-full px-3.5 py-2.5 text-xs font-bold text-slate-600 hover:text-emerald-700 hover:bg-slate-50 transition-colors flex items-center gap-2"
                >
                  <Edit className="h-4 w-4" strokeWidth={2.5} />
                  <span>Edit Details</span>
                </button>

                {row.status === 'archived' ? (
                  <button
                    type="button"
                    onClick={() => {
                      setActiveDropdownId(null);
                      handleOpenArchiveConfirm(row);
                    }}
                    className="w-full px-3.5 py-2.5 text-xs font-bold text-teal-600 hover:bg-teal-50 transition-colors flex items-center gap-2 border-t border-slate-50"
                  >
                    <RotateCcw className="h-4 w-4" strokeWidth={2.5} />
                    <span>Unarchive Book</span>
                  </button>
                ) : (
                  <button
                    type="button"
                    onClick={() => {
                      setActiveDropdownId(null);
                      handleOpenArchiveConfirm(row);
                    }}
                    className="w-full px-3.5 py-2.5 text-xs font-bold text-amber-600 hover:bg-amber-50 transition-colors flex items-center gap-2 border-t border-slate-50"
                  >
                    <Archive className="h-4 w-4" strokeWidth={2.5} />
                    <span>Archive Books</span>
                  </button>
                )}

                <button
                  type="button"
                  onClick={() => {
                    setActiveDropdownId(null);
                    handleOpenDeleteConfirm(row);
                  }}
                  className="w-full px-3.5 py-2.5 text-xs font-bold text-rose-600 hover:bg-rose-50/50 transition-colors flex items-center gap-2 border-t border-slate-50"
                >
                  <Trash2 className="h-4 w-4" strokeWidth={2.5} />
                  <span>Delete Books</span>
                </button>
              </div>
            )}
          </div>
        );
      }
    }
  ];

  const categories = [
    'Fiction',
    'Science',
    'History',
    'Biography',
    'Philosophy',
    'Technology',
    'Children'
  ];

  return (
    <div className="space-y-6 fade-in">
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-slate-800 tracking-tight leading-none mb-1">
            Book Inventory Manager
          </h2>
          <p className="text-xs text-slate-400 font-semibold">
            Catalog new arrivals, adjust copies levels, and edit book profiles
          </p>
        </div>

        <Button
          variant="primary"
          size="sm"
          onClick={handleOpenAdd}
          className="text-xs"
        >
          <Plus className="h-4 w-4 mr-2" />
          <span>Catalog New Book</span>
        </Button>
      </div>

      {/* Main registry Table */}
      {loading ? (
        <div className="flex flex-col items-center justify-center p-20 space-y-4">
          <svg className="animate-spin h-8 w-8 text-emerald-600" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
        </div>
      ) : (
        <DataTable
          columns={columns}
          data={books.filter(b => b.status !== 'archived')}
          searchPlaceholder="Filter registry by title, author, isbn..."
          searchField={(row) => `${row.title} ${row.author} ${row.isbn}`}
          initialSortKey="title"
          itemsPerPage={8}
        />
      )}

      {/* ADD BOOK MODAL */}
      <Modal
        isOpen={addModalOpen}
        onClose={() => setAddModalOpen(false)}
        title="Catalog New Title"
        footer={
          <>
            <Button
              type="button"
              variant="outline"
              onClick={() => setAddModalOpen(false)}
              className="h-11 px-5 text-xs font-bold"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="primary"
              form="add-book-form"
              isLoading={formLoading}
              className="h-11 px-6 text-xs font-bold"
            >
              Add Book
            </Button>
          </>
        }
      >
        <form id="add-book-form" onSubmit={handleAddSubmit} className="space-y-4.5">
          {feedback && (
            <div className="p-4 bg-rose-50 border border-rose-100 rounded-xl text-rose-600 flex items-start gap-2.5 text-xs font-semibold leading-relaxed">
              <Info className="h-4.5 w-4.5 flex-shrink-0 mt-0.5" />
              <span>{feedback.message}</span>
            </div>
          )}

          {/* ISBN Autofill Card */}
          <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl space-y-2.5">
            <div className="flex items-center gap-1.5">
              <Sparkles className="h-4 w-4 text-emerald-600" />
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wide">
                Smart Catalog via ISBN
              </label>
            </div>
            <div className="flex gap-2">
              <div className="relative flex-grow">
                <input
                  type="text"
                  placeholder="Enter 10 or 13 digit ISBN (e.g. 9780743273565)"
                  value={isbnInput}
                  onChange={(e) => setIsbnInput(e.target.value)}
                  className="input-field text-sm pr-8 bg-white border-slate-200"
                />
                {isbnInput && (
                  <button
                    type="button"
                    onClick={() => setIsbnInput('')}
                    className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                  >
                    <X className="h-4 w-4" />
                  </button>
                )}
              </div>
              <Button
                type="button"
                variant="outline"
                onClick={handleFetchBookDetails}
                disabled={fetchingDetails || !isbnInput.trim()}
                className="bg-white border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold text-xs flex-shrink-0 h-11 px-5 rounded-xl shadow-sm border"
              >
                {fetchingDetails ? (
                  <span className="flex items-center gap-1.5">
                    <Loader2 className="animate-spin h-3.5 w-3.5 text-emerald-600" />
                    Fetching...
                  </span>
                ) : (
                  <span className="flex items-center gap-1.5">
                    <Search className="h-3.5 w-3.5" />
                    Lookup
                  </span>
                )}
              </Button>
            </div>
            {fetchStatus && (
              <p className={`text-[11px] font-bold flex items-center gap-1 ${
                fetchStatus.type === 'success' ? 'text-emerald-600' : fetchStatus.type === 'info' ? 'text-emerald-600 animate-pulse' : 'text-rose-500'
              }`}>
                {fetchStatus.type === 'success' && <CheckCircle className="h-3.5 w-3.5 flex-shrink-0" />}
                {fetchStatus.type === 'error' && <XCircle className="h-3.5 w-3.5 flex-shrink-0" />}
                {fetchStatus.type === 'info' && <Loader2 className="h-3.5 w-3.5 flex-shrink-0 animate-spin" />}
                <span>{fetchStatus.message}</span>
              </p>
            )}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5 col-span-2">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Book Title *</label>
              <input type="text" name="title" required value={formData.title} onChange={handleInputChange} className="input-field text-sm" placeholder="The Great Gatsby" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Author *</label>
              <input type="text" name="author" required value={formData.author} onChange={handleInputChange} className="input-field text-sm" placeholder="F. Scott Fitzgerald" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">ISBN Code *</label>
              <input type="text" name="isbn" required value={formData.isbn} onChange={handleInputChange} className="input-field text-sm" placeholder="9780743273565" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Genre Category</label>
              <select name="category" value={formData.category} onChange={handleInputChange} className="input-field text-sm font-semibold text-slate-600">
                {categories.map((cat) => <option key={cat} value={cat}>{cat}</option>)}
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Publication Year *</label>
              <input type="number" name="year" required value={formData.year} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Total Copies Stock *</label>
              <input type="number" name="total_copies" required min={1} value={formData.total_copies} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Cover Image URL</label>
              <input type="text" name="cover_image" value={formData.cover_image} onChange={handleInputChange} className="input-field text-sm" placeholder="http://example.com/cover.jpg" />
            </div>

            <div className="space-y-1.5 col-span-2">
              <div className="flex items-center justify-between">
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Book Abstract Description</label>
                <button
                  type="button"
                  onClick={handleAutoGenerateDescription}
                  disabled={!formData.title || !formData.author}
                  className="px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200/50 text-[11px] font-bold rounded-xl flex items-center gap-1.5 transition-all duration-150 active:scale-95 disabled:opacity-40 disabled:pointer-events-none focus:outline-none shadow-sm shadow-emerald-50/50"
                  title="Generates a summary based on Title, Author, Genre and Publication Year"
                >
                  <Sparkles className="h-3.5 w-3.5 text-emerald-600" />
                  <span>Auto-Generate Abstract</span>
                </button>
              </div>
              <textarea name="description" value={formData.description} onChange={handleInputChange} rows={3} className="input-field text-sm py-2" placeholder="Summary synopsis of the book content..." />
            </div>
          </div>
        </form>
      </Modal>

      {/* EDIT BOOK MODAL */}
      <Modal
        isOpen={editModalOpen}
        onClose={() => setEditModalOpen(false)}
        title="Modify Book Metadata"
        footer={
          <>
            <Button
              type="button"
              variant="outline"
              onClick={() => setEditModalOpen(false)}
              className="h-11 px-5 text-xs font-bold"
            >
              Dismiss
            </Button>
            <Button
              type="submit"
              variant="primary"
              form="edit-book-form"
              isLoading={formLoading}
              className="h-11 px-6 text-xs font-bold"
            >
              Save Modifications
            </Button>
          </>
        }
      >
        <form id="edit-book-form" onSubmit={handleEditSubmit} className="space-y-4.5">
          {feedback && (
            <div className="p-4 bg-rose-50 border border-rose-100 rounded-xl text-rose-600 flex items-start gap-2.5 text-xs font-semibold leading-relaxed">
              <Info className="h-4.5 w-4.5 flex-shrink-0 mt-0.5" />
              <span>{feedback.message}</span>
            </div>
          )}

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5 col-span-2">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Book Title *</label>
              <input type="text" name="title" required value={formData.title} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Author *</label>
              <input type="text" name="author" required value={formData.author} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">ISBN Code *</label>
              <input type="text" name="isbn" required value={formData.isbn} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Genre Category</label>
              <select name="category" value={formData.category} onChange={handleInputChange} className="input-field text-sm font-semibold text-slate-600">
                {categories.map((cat) => <option key={cat} value={cat}>{cat}</option>)}
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Publication Year *</label>
              <input type="number" name="year" required value={formData.year} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Total Copies Stock *</label>
              <input type="number" name="total_copies" required min={1} value={formData.total_copies} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Cover Image URL</label>
              <input type="text" name="cover_image" value={formData.cover_image} onChange={handleInputChange} className="input-field text-sm" />
            </div>

            <div className="space-y-1.5 col-span-2">
              <div className="flex items-center justify-between">
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wide">Book Abstract Description</label>
                <button
                  type="button"
                  onClick={handleAutoGenerateDescription}
                  disabled={!formData.title || !formData.author}
                  className="px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200/50 text-[11px] font-bold rounded-xl flex items-center gap-1.5 transition-all duration-150 active:scale-95 disabled:opacity-40 disabled:pointer-events-none focus:outline-none shadow-sm shadow-emerald-50/50"
                  title="Generates a summary based on Title, Author, Genre and Publication Year"
                >
                  <Sparkles className="h-3.5 w-3.5 text-emerald-600" />
                  <span>Auto-Generate Abstract</span>
                </button>
              </div>
              <textarea name="description" value={formData.description} onChange={handleInputChange} rows={3} className="input-field text-sm py-2" />
            </div>
          </div>
        </form>
      </Modal>

      {/* DELETE CONFIRMATION MODAL */}
      <Modal
        isOpen={!!deleteConfirmBook}
        onClose={() => setDeleteConfirmBook(null)}
        title="Confirm Deletion"
        size="sm"
        footer={
          <div className="flex items-center justify-center gap-3 w-full">
            <Button
              type="button"
              variant="outline"
              onClick={() => setDeleteConfirmBook(null)}
              className="h-11 px-5 text-xs font-bold"
            >
              Cancel
            </Button>
            <Button
              type="button"
              variant="danger"
              onClick={() => {
                if (deleteConfirmBook) {
                  handleDeleteExecute(deleteConfirmBook);
                  setDeleteConfirmBook(null);
                }
              }}
              className="h-11 px-6 text-xs font-bold"
            >
              Delete
            </Button>
          </div>
        }
      >
        {deleteConfirmBook && (
          <div className="space-y-5 text-center px-4 pt-4 pb-2">
            <div className="mx-auto h-12 w-12 rounded-full bg-rose-50 border border-rose-100 flex items-center justify-center text-rose-600 mb-1 animate-pulse">
              <Trash2 className="h-6 w-6 text-rose-600" />
            </div>
            
            <div className="space-y-1.5">
              <h4 className="text-sm font-bold text-slate-800">Confirm Catalog Deletion</h4>
              <p className="text-xs text-slate-500 leading-relaxed max-w-sm mx-auto">
                Are you absolutely sure you want to permanently delete <span className="font-extrabold text-slate-700">"{deleteConfirmBook.title}"</span> from the catalog registry?
              </p>
            </div>
          </div>
        )}
      </Modal>

      {/* ARCHIVE/UNARCHIVE CONFIRMATION MODAL */}
      <Modal
        isOpen={!!archiveConfirmBook}
        onClose={() => setArchiveConfirmBook(null)}
        title={archiveConfirmBook?.status === 'archived' ? 'Unarchive Book' : 'Archive Book'}
        size="sm"
        footer={
          <div className="flex items-center justify-center gap-3 w-full">
            <Button
              type="button"
              variant="outline"
              onClick={() => setArchiveConfirmBook(null)}
              className="h-11 px-5 text-xs font-bold"
            >
              Cancel
            </Button>
            <Button
              type="button"
              variant="primary"
              isLoading={archiveLoading}
              onClick={() => {
                if (archiveConfirmBook) {
                  handleArchiveExecute(archiveConfirmBook);
                }
              }}
              className={`h-11 px-6 text-xs font-bold text-white border-transparent ${
                archiveConfirmBook?.status === 'archived'
                  ? 'bg-teal-600 hover:bg-teal-700 font-bold border-teal-600 shadow-md shadow-teal-100'
                  : 'bg-amber-600 hover:bg-amber-700 font-bold border-amber-600 shadow-md shadow-amber-100'
              }`}
            >
              {archiveConfirmBook?.status === 'archived' ? 'Unarchive' : 'Archive'}
            </Button>
          </div>
        }
      >
        {archiveConfirmBook && (
          <div className="space-y-5 text-center px-4 pt-4 pb-2">
            <div className={`mx-auto h-12 w-12 rounded-full border flex items-center justify-center mb-1 animate-pulse ${
              archiveConfirmBook.status === 'archived'
                ? 'bg-teal-50 border-teal-100 text-teal-600'
                : 'bg-amber-50 border-amber-100 text-amber-600'
            }`}>
              {archiveConfirmBook.status === 'archived'
                ? <RotateCcw className="h-6 w-6" />
                : <Archive className="h-6 w-6" />
              }
            </div>

            <div className="space-y-1.5">
              <h4 className="text-sm font-bold text-slate-800">
                {archiveConfirmBook.status === 'archived' ? 'Unarchive Book' : 'Archive Book'}
              </h4>
              <p className="text-xs text-slate-500 leading-relaxed max-w-sm mx-auto">
                {archiveConfirmBook.status === 'archived' ? (
                  <>
                    Are you sure you want to unarchive <span className="font-extrabold text-slate-700">"{archiveConfirmBook.title}"</span>? This will make it visible to members in the library catalog.
                  </>
                ) : (
                  <>
                    Are you sure you want to archive <span className="font-extrabold text-slate-700">"{archiveConfirmBook.title}"</span>? This will hide the title from members but preserve all past transaction logs.
                  </>
                )}
              </p>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default AdminBooks;
